name: Build and push

on:
  workflow_dispatch:
  workflow_call:

jobs:
  push:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read current version
        run: |
          echo "VERSION=$(awk -F "= " '/current_version / {print $2}' .bumpversion.cfg)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/petterhj/homeassistant-inkplate-dashboard:latest
            ghcr.io/petterhj/homeassistant-inkplate-dashboard:${{ env.VERSION }}
          build-args: |
            DOCKER_TAG=${{ env.VERSION }}
